# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sumsub_python_sdk import schemas  # noqa: F401


class ApplicantSubmitTransactionDataRequest1(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "counterparty",
            "applicant",
            "info",
            "txnId",
        }
        
        class properties:
        
            @staticmethod
            def info() -> typing.Type['ApplicantSubmitTransactionDataRequest1Info']:
                return ApplicantSubmitTransactionDataRequest1Info
            txnId = schemas.StrSchema
        
            @staticmethod
            def applicant() -> typing.Type['ApplicantSubmitTransactionDataRequest1Applicant']:
                return ApplicantSubmitTransactionDataRequest1Applicant
        
            @staticmethod
            def counterparty() -> typing.Type['ApplicantSubmitTransactionDataRequest1Counterparty']:
                return ApplicantSubmitTransactionDataRequest1Counterparty
            txnDate = schemas.DateSchema
            type = schemas.StrSchema
            sourceKey = schemas.StrSchema
        
            @staticmethod
            def props() -> typing.Type['ApplicantSubmitTransactionDataRequest1Props']:
                return ApplicantSubmitTransactionDataRequest1Props
            __annotations__ = {
                "info": info,
                "txnId": txnId,
                "applicant": applicant,
                "counterparty": counterparty,
                "txnDate": txnDate,
                "type": type,
                "sourceKey": sourceKey,
                "props": props,
            }
    
    counterparty: 'ApplicantSubmitTransactionDataRequest1Counterparty'
    applicant: 'ApplicantSubmitTransactionDataRequest1Applicant'
    info: 'ApplicantSubmitTransactionDataRequest1Info'
    txnId: MetaOapg.properties.txnId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["info"]) -> 'ApplicantSubmitTransactionDataRequest1Info': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["txnId"]) -> MetaOapg.properties.txnId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["applicant"]) -> 'ApplicantSubmitTransactionDataRequest1Applicant': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["counterparty"]) -> 'ApplicantSubmitTransactionDataRequest1Counterparty': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["txnDate"]) -> MetaOapg.properties.txnDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sourceKey"]) -> MetaOapg.properties.sourceKey: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["props"]) -> 'ApplicantSubmitTransactionDataRequest1Props': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["info", "txnId", "applicant", "counterparty", "txnDate", "type", "sourceKey", "props", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["info"]) -> 'ApplicantSubmitTransactionDataRequest1Info': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["txnId"]) -> MetaOapg.properties.txnId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["applicant"]) -> 'ApplicantSubmitTransactionDataRequest1Applicant': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["counterparty"]) -> 'ApplicantSubmitTransactionDataRequest1Counterparty': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["txnDate"]) -> typing.Union[MetaOapg.properties.txnDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sourceKey"]) -> typing.Union[MetaOapg.properties.sourceKey, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["props"]) -> typing.Union['ApplicantSubmitTransactionDataRequest1Props', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["info", "txnId", "applicant", "counterparty", "txnDate", "type", "sourceKey", "props", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        counterparty: 'ApplicantSubmitTransactionDataRequest1Counterparty',
        applicant: 'ApplicantSubmitTransactionDataRequest1Applicant',
        info: 'ApplicantSubmitTransactionDataRequest1Info',
        txnId: typing.Union[MetaOapg.properties.txnId, str, ],
        txnDate: typing.Union[MetaOapg.properties.txnDate, str, date, schemas.Unset] = schemas.unset,
        type: typing.Union[MetaOapg.properties.type, str, schemas.Unset] = schemas.unset,
        sourceKey: typing.Union[MetaOapg.properties.sourceKey, str, schemas.Unset] = schemas.unset,
        props: typing.Union['ApplicantSubmitTransactionDataRequest1Props', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ApplicantSubmitTransactionDataRequest1':
        return super().__new__(
            cls,
            *args,
            counterparty=counterparty,
            applicant=applicant,
            info=info,
            txnId=txnId,
            txnDate=txnDate,
            type=type,
            sourceKey=sourceKey,
            props=props,
            _configuration=_configuration,
            **kwargs,
        )

from sumsub_python_sdk.model.applicant_submit_transaction_data_request1_applicant import ApplicantSubmitTransactionDataRequest1Applicant
from sumsub_python_sdk.model.applicant_submit_transaction_data_request1_counterparty import ApplicantSubmitTransactionDataRequest1Counterparty
from sumsub_python_sdk.model.applicant_submit_transaction_data_request1_info import ApplicantSubmitTransactionDataRequest1Info
from sumsub_python_sdk.model.applicant_submit_transaction_data_request1_props import ApplicantSubmitTransactionDataRequest1Props
