# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sumsub_python_sdk import schemas  # noqa: F401


class ApplicantImportCompletedRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def info() -> typing.Type['ApplicantImportCompletedRequestInfo']:
                return ApplicantImportCompletedRequestInfo
            externalUserId = schemas.StrSchema
        
            @staticmethod
            def review() -> typing.Type['ApplicantImportCompletedRequestReview']:
                return ApplicantImportCompletedRequestReview
            __annotations__ = {
                "info": info,
                "externalUserId": externalUserId,
                "review": review,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["info"]) -> 'ApplicantImportCompletedRequestInfo': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["externalUserId"]) -> MetaOapg.properties.externalUserId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["review"]) -> 'ApplicantImportCompletedRequestReview': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["info", "externalUserId", "review", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["info"]) -> typing.Union['ApplicantImportCompletedRequestInfo', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["externalUserId"]) -> typing.Union[MetaOapg.properties.externalUserId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["review"]) -> typing.Union['ApplicantImportCompletedRequestReview', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["info", "externalUserId", "review", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        info: typing.Union['ApplicantImportCompletedRequestInfo', schemas.Unset] = schemas.unset,
        externalUserId: typing.Union[MetaOapg.properties.externalUserId, str, schemas.Unset] = schemas.unset,
        review: typing.Union['ApplicantImportCompletedRequestReview', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ApplicantImportCompletedRequest':
        return super().__new__(
            cls,
            *args,
            info=info,
            externalUserId=externalUserId,
            review=review,
            _configuration=_configuration,
            **kwargs,
        )

from sumsub_python_sdk.model.applicant_import_completed_request_info import ApplicantImportCompletedRequestInfo
from sumsub_python_sdk.model.applicant_import_completed_request_review import ApplicantImportCompletedRequestReview
