# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sumsub_python_sdk import schemas  # noqa: F401


class ApplicantUpdateTopLevelInfoRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "id",
        }
        
        class properties:
            id = schemas.StrSchema
            externalUserId = schemas.StrSchema
            email = schemas.StrSchema
            phone = schemas.StrSchema
            sourceKey = schemas.StrSchema
            lang = schemas.StrSchema
        
            @staticmethod
            def questionnaires() -> typing.Type['ApplicantUpdateTopLevelInfoRequestQuestionnaires']:
                return ApplicantUpdateTopLevelInfoRequestQuestionnaires
        
            @staticmethod
            def metadata() -> typing.Type['ApplicantUpdateTopLevelInfoRequestMetadata']:
                return ApplicantUpdateTopLevelInfoRequestMetadata
            deleted = schemas.BoolSchema
            __annotations__ = {
                "id": id,
                "externalUserId": externalUserId,
                "email": email,
                "phone": phone,
                "sourceKey": sourceKey,
                "lang": lang,
                "questionnaires": questionnaires,
                "metadata": metadata,
                "deleted": deleted,
            }
    
    id: MetaOapg.properties.id
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["externalUserId"]) -> MetaOapg.properties.externalUserId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phone"]) -> MetaOapg.properties.phone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sourceKey"]) -> MetaOapg.properties.sourceKey: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lang"]) -> MetaOapg.properties.lang: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["questionnaires"]) -> 'ApplicantUpdateTopLevelInfoRequestQuestionnaires': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> 'ApplicantUpdateTopLevelInfoRequestMetadata': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deleted"]) -> MetaOapg.properties.deleted: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "externalUserId", "email", "phone", "sourceKey", "lang", "questionnaires", "metadata", "deleted", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["externalUserId"]) -> typing.Union[MetaOapg.properties.externalUserId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> typing.Union[MetaOapg.properties.email, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phone"]) -> typing.Union[MetaOapg.properties.phone, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sourceKey"]) -> typing.Union[MetaOapg.properties.sourceKey, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lang"]) -> typing.Union[MetaOapg.properties.lang, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["questionnaires"]) -> typing.Union['ApplicantUpdateTopLevelInfoRequestQuestionnaires', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> typing.Union['ApplicantUpdateTopLevelInfoRequestMetadata', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deleted"]) -> typing.Union[MetaOapg.properties.deleted, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "externalUserId", "email", "phone", "sourceKey", "lang", "questionnaires", "metadata", "deleted", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, str, ],
        externalUserId: typing.Union[MetaOapg.properties.externalUserId, str, schemas.Unset] = schemas.unset,
        email: typing.Union[MetaOapg.properties.email, str, schemas.Unset] = schemas.unset,
        phone: typing.Union[MetaOapg.properties.phone, str, schemas.Unset] = schemas.unset,
        sourceKey: typing.Union[MetaOapg.properties.sourceKey, str, schemas.Unset] = schemas.unset,
        lang: typing.Union[MetaOapg.properties.lang, str, schemas.Unset] = schemas.unset,
        questionnaires: typing.Union['ApplicantUpdateTopLevelInfoRequestQuestionnaires', schemas.Unset] = schemas.unset,
        metadata: typing.Union['ApplicantUpdateTopLevelInfoRequestMetadata', schemas.Unset] = schemas.unset,
        deleted: typing.Union[MetaOapg.properties.deleted, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ApplicantUpdateTopLevelInfoRequest':
        return super().__new__(
            cls,
            *args,
            id=id,
            externalUserId=externalUserId,
            email=email,
            phone=phone,
            sourceKey=sourceKey,
            lang=lang,
            questionnaires=questionnaires,
            metadata=metadata,
            deleted=deleted,
            _configuration=_configuration,
            **kwargs,
        )

from sumsub_python_sdk.model.applicant_update_top_level_info_request_metadata import ApplicantUpdateTopLevelInfoRequestMetadata
from sumsub_python_sdk.model.applicant_update_top_level_info_request_questionnaires import ApplicantUpdateTopLevelInfoRequestQuestionnaires
