# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sumsub_python_sdk import schemas  # noqa: F401


class TransactionBulkImportRequestData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    An object representing the transaction. For more information on the structure, see [Submit transaction for existing applicant](ref:submit-transaction-for-existing-applicant).
    """


    class MetaOapg:
        required = {
            "txnId",
        }
        
        class properties:
            txnId = schemas.StrSchema
        
            @staticmethod
            def info() -> typing.Type['TransactionBulkImportRequestDataInfo']:
                return TransactionBulkImportRequestDataInfo
            txnDate = schemas.DateSchema
            props = schemas.StrSchema
        
            @staticmethod
            def applicant() -> typing.Type['TransactionBulkImportRequestDataApplicant']:
                return TransactionBulkImportRequestDataApplicant
        
            @staticmethod
            def counterparty() -> typing.Type['TransactionBulkImportRequestDataCounterparty']:
                return TransactionBulkImportRequestDataCounterparty
            type = schemas.StrSchema
            sourceKey = schemas.StrSchema
            __annotations__ = {
                "txnId": txnId,
                "info": info,
                "txnDate": txnDate,
                "props": props,
                "applicant": applicant,
                "counterparty": counterparty,
                "type": type,
                "sourceKey": sourceKey,
            }
    
    txnId: MetaOapg.properties.txnId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["txnId"]) -> MetaOapg.properties.txnId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["info"]) -> 'TransactionBulkImportRequestDataInfo': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["txnDate"]) -> MetaOapg.properties.txnDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["props"]) -> MetaOapg.properties.props: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["applicant"]) -> 'TransactionBulkImportRequestDataApplicant': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["counterparty"]) -> 'TransactionBulkImportRequestDataCounterparty': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sourceKey"]) -> MetaOapg.properties.sourceKey: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["txnId", "info", "txnDate", "props", "applicant", "counterparty", "type", "sourceKey", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["txnId"]) -> MetaOapg.properties.txnId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["info"]) -> typing.Union['TransactionBulkImportRequestDataInfo', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["txnDate"]) -> typing.Union[MetaOapg.properties.txnDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["props"]) -> typing.Union[MetaOapg.properties.props, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["applicant"]) -> typing.Union['TransactionBulkImportRequestDataApplicant', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["counterparty"]) -> typing.Union['TransactionBulkImportRequestDataCounterparty', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sourceKey"]) -> typing.Union[MetaOapg.properties.sourceKey, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["txnId", "info", "txnDate", "props", "applicant", "counterparty", "type", "sourceKey", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        txnId: typing.Union[MetaOapg.properties.txnId, str, ],
        info: typing.Union['TransactionBulkImportRequestDataInfo', schemas.Unset] = schemas.unset,
        txnDate: typing.Union[MetaOapg.properties.txnDate, str, date, schemas.Unset] = schemas.unset,
        props: typing.Union[MetaOapg.properties.props, str, schemas.Unset] = schemas.unset,
        applicant: typing.Union['TransactionBulkImportRequestDataApplicant', schemas.Unset] = schemas.unset,
        counterparty: typing.Union['TransactionBulkImportRequestDataCounterparty', schemas.Unset] = schemas.unset,
        type: typing.Union[MetaOapg.properties.type, str, schemas.Unset] = schemas.unset,
        sourceKey: typing.Union[MetaOapg.properties.sourceKey, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TransactionBulkImportRequestData':
        return super().__new__(
            cls,
            *args,
            txnId=txnId,
            info=info,
            txnDate=txnDate,
            props=props,
            applicant=applicant,
            counterparty=counterparty,
            type=type,
            sourceKey=sourceKey,
            _configuration=_configuration,
            **kwargs,
        )

from sumsub_python_sdk.model.transaction_bulk_import_request_data_applicant import TransactionBulkImportRequestDataApplicant
from sumsub_python_sdk.model.transaction_bulk_import_request_data_counterparty import TransactionBulkImportRequestDataCounterparty
from sumsub_python_sdk.model.transaction_bulk_import_request_data_info import TransactionBulkImportRequestDataInfo
