# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sumsub_python_sdk.type.applicant_change_company_data_request_addresses import ApplicantChangeCompanyDataRequestAddresses
from sumsub_python_sdk.type.applicant_change_company_data_request_beneficiaries import ApplicantChangeCompanyDataRequestBeneficiaries

class RequiredApplicantChangeCompanyDataRequest(TypedDict):
    # Name of the company.
    companyName: str

    # Registration number.
    registrationNumber: str

class OptionalApplicantChangeCompanyDataRequest(TypedDict, total=False):
    # A three-letter country code (e.g. `DEU`).
    country: str

    # Legal name.
    legalAddress: str

    # Date of incorporation (format `YYYY-mm-dd`, e.g. 2001-09-25).
    incorporatedOn: str

    # Type of entity.
    type: str

    # Email address.
    email: str

    # Description of the control scheme of the group of entities.
    controlScheme: str

    # Phone number.
    phone: str

    # Taxpayer registration number/Code of taxpayer registration.
    taxId: str

    # Location of registration.
    registrationLocation: str

    # Website's URL.
    website: str

    # Postal address.
    postalAddress: str

    beneficiaries: ApplicantChangeCompanyDataRequestBeneficiaries

    addresses: ApplicantChangeCompanyDataRequestAddresses

class ApplicantChangeCompanyDataRequest(RequiredApplicantChangeCompanyDataRequest, OptionalApplicantChangeCompanyDataRequest):
    pass
