# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sumsub_python_sdk.type.applicant_import_completed_request1_info import ApplicantImportCompletedRequest1Info
from sumsub_python_sdk.type.applicant_import_completed_request1_review import ApplicantImportCompletedRequest1Review

class RequiredApplicantImportCompletedRequest1(TypedDict):
    pass

class OptionalApplicantImportCompletedRequest1(TypedDict, total=False):
    info: ApplicantImportCompletedRequest1Info

    # someClientUserId
    externalUserId: str

    review: ApplicantImportCompletedRequest1Review

class ApplicantImportCompletedRequest1(RequiredApplicantImportCompletedRequest1, OptionalApplicantImportCompletedRequest1):
    pass
