# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredApplicantChangeExtractedInfoRequest1(TypedDict):
    pass

class OptionalApplicantChangeExtractedInfoRequest1(TypedDict, total=False):
    # The first name of the applicant.
    firstName: str

    # The last name of the applicant.
    lastName: str

    # The middle name of the applicant.
    middleName: str

    # Legal name.
    legalName: str

    # An applicant gender (`M` or `F`).
    gender: str

    # Applicant date of birth (format `YYYY-mm-dd`, e.g. 2001-09-25).
    dob: str

    # The applicant birthplace.
    placeOfBirth: str

    # Applicant country of birth.
    countryOfBirth: str

    # Applicant state of birth.
    stateOfBirth: str

    # Alpha-3 country code (e.g. `DEU` or `GBR`).
    country: str

    # Alpha-3 country code.
    nationality: str

    # List of applicant addresses.
    addresses: str

    # Tax identification number.
    tin: str

class ApplicantChangeExtractedInfoRequest1(RequiredApplicantChangeExtractedInfoRequest1, OptionalApplicantChangeExtractedInfoRequest1):
    pass
