# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sumsub_python_sdk.type.applicant_import_completed_request_review_review import ApplicantImportCompletedRequestReviewReview

class RequiredApplicantImportCompletedRequestReview(TypedDict):
    pass

class OptionalApplicantImportCompletedRequestReview(TypedDict, total=False):
    # Date of users' creation on your side in a format: \"2022-11-21 08:25:32+0000\"
    createDate: str

    # review date on your side in a format: \"2022-11-21 08:25:32+0000\"
    reviewDate: str

    review: ApplicantImportCompletedRequestReviewReview

    # \"completed\"
    reviewStatus: str

class ApplicantImportCompletedRequestReview(RequiredApplicantImportCompletedRequestReview, OptionalApplicantImportCompletedRequestReview):
    pass
