# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sumsub_python_sdk.type.applicant_create_action_request1_payment_method_data import ApplicantCreateActionRequest1PaymentMethodData

class RequiredApplicantCreateActionRequest1PaymentMethod(TypedDict):
    # A payment type. Can be: `bankCard`, `eWallet`, `wireTransfer`.
    type: str

class OptionalApplicantCreateActionRequest1PaymentMethod(TypedDict, total=False):
    # A payment subtype. For example, `VISA`, `MASTERCARD`, etc.
    subType: str

    data: ApplicantCreateActionRequest1PaymentMethodData

class ApplicantCreateActionRequest1PaymentMethod(RequiredApplicantCreateActionRequest1PaymentMethod, OptionalApplicantCreateActionRequest1PaymentMethod):
    pass
