# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sumsub_python_sdk.type.transaction_bulk_import_request1_data_applicant import TransactionBulkImportRequest1DataApplicant
from sumsub_python_sdk.type.transaction_bulk_import_request1_data_counterparty import TransactionBulkImportRequest1DataCounterparty
from sumsub_python_sdk.type.transaction_bulk_import_request1_data_info import TransactionBulkImportRequest1DataInfo

class RequiredTransactionBulkImportRequest1Data(TypedDict):
    # A unique transaction identifier.
    txnId: str

class OptionalTransactionBulkImportRequest1Data(TypedDict, total=False):
    info: TransactionBulkImportRequest1DataInfo

    # Time when the transaction was initiated (format `yyyy-MM-dd HH:mm:ss+XXXX`, e.g. 2022-11-24 23:37:02+0000).
    txnDate: date

    # Transaction properties. Map of strings - JSON of custom keys and string values.
    props: str

    applicant: TransactionBulkImportRequest1DataApplicant

    counterparty: TransactionBulkImportRequest1DataCounterparty

    # Transaction type. Takes predefined values: `finance`/`gamblingBet`/`gamblingLimitChange`/`kyc`/`login`/`signup`/`passwordChange`/`twoFaReset`/`travelRule` (`finance` by default).
    type: str

    # Source Key indication to separate accesses to transactions.
    sourceKey: str

class TransactionBulkImportRequest1Data(RequiredTransactionBulkImportRequest1Data, OptionalTransactionBulkImportRequest1Data):
    pass
