# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTransactionBulkImportRequest1DataInfo(TypedDict):
    # Can be `out` (applicant sends to counterparty) or `in` (counterparty sends to applicant).
    direction: str

    # The amount of funds used in this transaction.
    amount: typing.Union[int, float]

    # Currency code (`USD`, `GBP`, `BTC`, etc).
    currencyCode: str

class OptionalTransactionBulkImportRequest1DataInfo(TypedDict, total=False):
    # The amount of funds used in this transaction in the default currency. For more precise calculations, you can submit already converted default currency amount in this field.
    amountInDefaultCurrency: typing.Union[int, float]

    # The crypto chain name. Mandatory for crypto tokens only. Specifies the network name to which the token at `currencyCode` belongs. Empty for native tokens (e.g. for `BTC`, `ETH`). For more information, see [chain codes](ref:crypto-chain-codes).
    cryptoChain: str

    # Crypto transaction ID from the blockchain. Required for crypto check requests only.
    paymentTxnId: str

    # A comment with payment details.
    paymentDetails: str

    # Accepts any value that helps you categorize transactions. For example, for gambling transactions, you can specify `bonus`, `payroll`, or `cashback`.
    type: str

class TransactionBulkImportRequest1DataInfo(RequiredTransactionBulkImportRequest1DataInfo, OptionalTransactionBulkImportRequest1DataInfo):
    pass
