# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sumsub_python_sdk.type.transaction_bulk_import_request1_data_counterparty_institution_info_address import TransactionBulkImportRequest1DataCounterpartyInstitutionInfoAddress

class RequiredTransactionBulkImportRequest1DataCounterpartyInstitutionInfo(TypedDict):
    pass

class OptionalTransactionBulkImportRequest1DataCounterpartyInstitutionInfo(TypedDict, total=False):
    # Transaction institution code.
    code: str

    # Transaction institution name.
    name: str

    address: TransactionBulkImportRequest1DataCounterpartyInstitutionInfoAddress

    # VASP ID for counterparty transaction. If provided, we trust the exchange and use the expected VASP for transaction approval.
    internalId: str

class TransactionBulkImportRequest1DataCounterpartyInstitutionInfo(RequiredTransactionBulkImportRequest1DataCounterpartyInstitutionInfo, OptionalTransactionBulkImportRequest1DataCounterpartyInstitutionInfo):
    pass
