# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import sumsub_python_sdk
from sumsub_python_sdk.model.applicant_submit_transaction_for_non_existing_request1_applicant_institution_info_address import ApplicantSubmitTransactionForNonExistingRequest1ApplicantInstitutionInfoAddress
from sumsub_python_sdk import configuration


class TestApplicantSubmitTransactionForNonExistingRequest1ApplicantInstitutionInfoAddress(unittest.TestCase):
    """ApplicantSubmitTransactionForNonExistingRequest1ApplicantInstitutionInfoAddress unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
