# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from sumsub_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from sumsub_python_sdk.api_response import AsyncGeneratorResponse
from sumsub_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sumsub_python_sdk import schemas  # noqa: F401

from sumsub_python_sdk.model.transaction_bulk_import_request_data import TransactionBulkImportRequestData as TransactionBulkImportRequestDataSchema
from sumsub_python_sdk.model.transaction_bulk_import_request import TransactionBulkImportRequest as TransactionBulkImportRequestSchema
from sumsub_python_sdk.model.transaction_bulk_import_request1 import TransactionBulkImportRequest1 as TransactionBulkImportRequest1Schema

from sumsub_python_sdk.type.transaction_bulk_import_request import TransactionBulkImportRequest
from sumsub_python_sdk.type.transaction_bulk_import_request_data import TransactionBulkImportRequestData
from sumsub_python_sdk.type.transaction_bulk_import_request1 import TransactionBulkImportRequest1

from ...api_client import Dictionary
from sumsub_python_sdk.pydantic.transaction_bulk_import_request import TransactionBulkImportRequest as TransactionBulkImportRequestPydantic
from sumsub_python_sdk.pydantic.transaction_bulk_import_request_data import TransactionBulkImportRequestData as TransactionBulkImportRequestDataPydantic
from sumsub_python_sdk.pydantic.transaction_bulk_import_request1 import TransactionBulkImportRequest1 as TransactionBulkImportRequest1Pydantic

# Query params
IgnoreErrorsSchema = schemas.BoolSchema
ScoreSavedTxnsSchema = schemas.BoolSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'ignoreErrors': typing.Union[IgnoreErrorsSchema, bool, ],
        'scoreSavedTxns': typing.Union[ScoreSavedTxnsSchema, bool, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_ignore_errors = api_client.QueryParameter(
    name="ignoreErrors",
    style=api_client.ParameterStyle.FORM,
    schema=IgnoreErrorsSchema,
    explode=True,
)
request_query_score_saved_txns = api_client.QueryParameter(
    name="scoreSavedTxns",
    style=api_client.ParameterStyle.FORM,
    schema=ScoreSavedTxnsSchema,
    explode=True,
)
# body param
SchemaForRequestBodyApplicationJson = TransactionBulkImportRequestSchema
SchemaForRequestBodyMultipartFormData = TransactionBulkImportRequest1Schema


request_body_transaction_bulk_import_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
        'multipart/form-data': api_client.MediaType(
            schema=SchemaForRequestBodyMultipartFormData),
    },
)


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
)


class BaseApi(api_client.Api):

    def _bulk_import_mapped_args(
        self,
        applicant_id: str,
        data: TransactionBulkImportRequestData,
        ignore_errors: typing.Optional[bool] = None,
        score_saved_txns: typing.Optional[bool] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _body = {}
        if applicant_id is not None:
            _body["applicantId"] = applicant_id
        if data is not None:
            _body["data"] = data
        args.body = _body
        if ignore_errors is not None:
            _query_params["ignoreErrors"] = ignore_errors
        if score_saved_txns is not None:
            _query_params["scoreSavedTxns"] = score_saved_txns
        args.query = _query_params
        return args

    async def _abulk_import_oapg(
        self,
        body: typing.Any = None,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Bulk transaction import
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_ignore_errors,
            request_query_score_saved_txns,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/resources/kyt/misc/txns/import',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_transaction_bulk_import_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _bulk_import_oapg(
        self,
        body: typing.Any = None,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Bulk transaction import
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_ignore_errors,
            request_query_score_saved_txns,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/resources/kyt/misc/txns/import',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_transaction_bulk_import_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class BulkImportRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def abulk_import(
        self,
        applicant_id: str,
        data: TransactionBulkImportRequestData,
        ignore_errors: typing.Optional[bool] = None,
        score_saved_txns: typing.Optional[bool] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._bulk_import_mapped_args(
            applicant_id=applicant_id,
            data=data,
            ignore_errors=ignore_errors,
            score_saved_txns=score_saved_txns,
        )
        return await self._abulk_import_oapg(
            body=args.body,
            query_params=args.query,
            **kwargs,
        )
    
    def bulk_import(
        self,
        applicant_id: str,
        data: TransactionBulkImportRequestData,
        ignore_errors: typing.Optional[bool] = None,
        score_saved_txns: typing.Optional[bool] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._bulk_import_mapped_args(
            applicant_id=applicant_id,
            data=data,
            ignore_errors=ignore_errors,
            score_saved_txns=score_saved_txns,
        )
        return self._bulk_import_oapg(
            body=args.body,
            query_params=args.query,
        )

class BulkImport(BaseApi):

    async def abulk_import(
        self,
        applicant_id: str,
        data: TransactionBulkImportRequestData,
        ignore_errors: typing.Optional[bool] = None,
        score_saved_txns: typing.Optional[bool] = None,
        validate: bool = False,
        **kwargs,
    ) -> None:
        raw_response = await self.raw.abulk_import(
            applicant_id=applicant_id,
            data=data,
            ignore_errors=ignore_errors,
            score_saved_txns=score_saved_txns,
            **kwargs,
        )
    
    
    def bulk_import(
        self,
        applicant_id: str,
        data: TransactionBulkImportRequestData,
        ignore_errors: typing.Optional[bool] = None,
        score_saved_txns: typing.Optional[bool] = None,
        validate: bool = False,
    ) -> None:
        raw_response = self.raw.bulk_import(
            applicant_id=applicant_id,
            data=data,
            ignore_errors=ignore_errors,
            score_saved_txns=score_saved_txns,
        )


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        applicant_id: str,
        data: TransactionBulkImportRequestData,
        ignore_errors: typing.Optional[bool] = None,
        score_saved_txns: typing.Optional[bool] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._bulk_import_mapped_args(
            applicant_id=applicant_id,
            data=data,
            ignore_errors=ignore_errors,
            score_saved_txns=score_saved_txns,
        )
        return await self._abulk_import_oapg(
            body=args.body,
            query_params=args.query,
            **kwargs,
        )
    
    def post(
        self,
        applicant_id: str,
        data: TransactionBulkImportRequestData,
        ignore_errors: typing.Optional[bool] = None,
        score_saved_txns: typing.Optional[bool] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._bulk_import_mapped_args(
            applicant_id=applicant_id,
            data=data,
            ignore_errors=ignore_errors,
            score_saved_txns=score_saved_txns,
        )
        return self._bulk_import_oapg(
            body=args.body,
            query_params=args.query,
        )

