# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sumsub_python_sdk.paths.resources_applicants_applicant_id_info_company_info_beneficiaries.post import AddBeneficiary
from sumsub_python_sdk.paths.resources_applicants_applicant_id_agreement.post import AddConsentToProfile
from sumsub_python_sdk.paths.resources_applicants_applicant_id_tags_add.post import AddCustomTags
from sumsub_python_sdk.paths.resources_applicants_applicant_id_tags.post import AddCustomTags0
from sumsub_python_sdk.paths.resources_applicants_applicant_id_info_id_doc.post import AddIdDocument
from sumsub_python_sdk.paths.resources_applicant_actions_action_id_images.post import AddImageToPaymentMethod
from sumsub_python_sdk.paths.resources_applicant_actions_action_id_payment_method.post import AddPaymentMethodInformation
from sumsub_python_sdk.paths.resources_applicants_applicant_id_blacklistnotenote.post import AddToBlocklist
from sumsub_python_sdk.paths.resources_applicants_applicant_id_info_company_info.patch import ChangeCompanyData
from sumsub_python_sdk.paths.resources_applicants_applicant_id_info.patch import ChangeExtractedInfo
from sumsub_python_sdk.paths.resources_applicants_applicant_id_move_to_level.post import ChangeRequiredDocumentSet
from sumsub_python_sdk.paths.resources_moderation_states__applicant_idapplicant_id.get import ClarifyRejectionReason
from sumsub_python_sdk.paths.resources_applicants_applicant_id_ekyc_confirm_confirmationid.post import ConfirmData
from sumsub_python_sdk.paths.resources_applicant_actions___for_applicant_applicant_idlevel_namelevel_name.post import CreateAction
from sumsub_python_sdk.paths.resources_applicant_actions___for_applicant_applicant_id_crypto_source_of_funds.post import CreateCryptoSourceOfFunds
from sumsub_python_sdk.paths.resources_applicant_actions___for_applicant_applicant_id_level_namepayment_source.post import CreatePaymentSourceActions
from sumsub_python_sdk.paths.resources_applicants_applicant_id_presence_status.patch import DeactivateProfile
from sumsub_python_sdk.paths.resources_kyt_txns_txn_id_data_applicant.patch import EnrichTransactionWithTravelRuleData
from sumsub_python_sdk.paths.resources_applicant_actions_action_id_one.get import GetActionOneInfo
from sumsub_python_sdk.paths.resources_applicant_actions__applicant_idapplicant_id.get import GetActions
from sumsub_python_sdk.paths.resources_applicant_actions_action_id_images_image_idpreviewis_preview.get import GetBankCardImage
from sumsub_python_sdk.paths.resources_applicants_applicant_id_one.get import GetData
from sumsub_python_sdk.paths.resources_applicants__external_user_idexternal_user_id_one.get import GetDataByExternalUserId
from sumsub_python_sdk.paths.resources_checks_latest.get import GetDataLatest
from sumsub_python_sdk.paths.resources_applicant_fraud_networks_network_id_one.get import GetFraudNetworkById
from sumsub_python_sdk.paths.resources_applicant_fraud_networks.get import GetFraudNetworks
from sumsub_python_sdk.paths.resources_applicant_fraud_networks___by_applicant_applicant_id.get import GetFraudNetworksByApplicant
from sumsub_python_sdk.paths.resources_applicants___levels.get import GetLevels
from sumsub_python_sdk.paths.resources_applicants_applicant_id_required_id_docs.post import GetRequiredIdDocs
from sumsub_python_sdk.paths.resources_applicants_applicant_id_status.get import GetReviewStatus
from sumsub_python_sdk.paths.resources_applicants_applicant_id_required_id_docs_status.get import GetVerificationStepsStatus
from sumsub_python_sdk.paths.resources_video_ident_applicant_applicant_id_media_composition_media_id.get import GetVideoCallMedia
from sumsub_python_sdk.paths.resources_applicants___applicant_import.post import ImportByArchive
from sumsub_python_sdk.paths.resources_applicants___ingest_completedlevel_namelevel_name.post import ImportCompleted
from sumsub_python_sdk.paths.resources_applicants_applicant_id_status_pendingreasonreason.post import InitiateApplicantCheck
from sumsub_python_sdk.paths.resources_kyt_txns_txn_id_applicant_id_applicant_id.post import MoveTransactionToAnotherApplicant
from sumsub_python_sdk.paths.resources_applicants_applicant_id_tags.delete import RemoveCustomTags
from sumsub_python_sdk.paths.resources_applicants_applicant_id_info_company_info_beneficiaries_beneficiary_applicant_id.delete import RemoveFromBeneficiaryList
from sumsub_python_sdk.paths.resources_applicant_actions_action_id_review_status_pending.post import RequestActionCheck
from sumsub_python_sdk.paths.resources_applicants_applicant_id_reset.post import ResetProfile
from sumsub_python_sdk.paths.resources_applicants_applicant_id_reset_step_id_doc_set_type.post import ResetVerificationStep
from sumsub_python_sdk.paths.resources_applicants_applicant_id_status_test_completed.post import SandboxVerificationResponse
from sumsub_python_sdk.paths.resources_applicants_applicant_id_ekyc_submit.post import SubmitDataNoDocVerification
from sumsub_python_sdk.paths.resources_applicant_actions___for_applicant_applicant_id_payment_method.post import SubmitPaymentMethod
from sumsub_python_sdk.paths.resources_applicants_applicant_id_kyt_txns___data.post import SubmitTransactionData
from sumsub_python_sdk.paths.resources_applicants___kyt_txns___data.post import SubmitTransactionForNonExisting
from sumsub_python_sdk.paths.resources_applicants_applicant_id_fixed_info.patch import UpdateFixedInfo
from sumsub_python_sdk.paths.resources_applicants.patch import UpdateTopLevelInfo
from sumsub_python_sdk.apis.tags.applicant_api_raw import ApplicantApiRaw


class ApplicantApi(
    AddBeneficiary,
    AddConsentToProfile,
    AddCustomTags,
    AddCustomTags0,
    AddIdDocument,
    AddImageToPaymentMethod,
    AddPaymentMethodInformation,
    AddToBlocklist,
    ChangeCompanyData,
    ChangeExtractedInfo,
    ChangeRequiredDocumentSet,
    ClarifyRejectionReason,
    ConfirmData,
    CreateAction,
    CreateCryptoSourceOfFunds,
    CreatePaymentSourceActions,
    DeactivateProfile,
    EnrichTransactionWithTravelRuleData,
    GetActionOneInfo,
    GetActions,
    GetBankCardImage,
    GetData,
    GetDataByExternalUserId,
    GetDataLatest,
    GetFraudNetworkById,
    GetFraudNetworks,
    GetFraudNetworksByApplicant,
    GetLevels,
    GetRequiredIdDocs,
    GetReviewStatus,
    GetVerificationStepsStatus,
    GetVideoCallMedia,
    ImportByArchive,
    ImportCompleted,
    InitiateApplicantCheck,
    MoveTransactionToAnotherApplicant,
    RemoveCustomTags,
    RemoveFromBeneficiaryList,
    RequestActionCheck,
    ResetProfile,
    ResetVerificationStep,
    SandboxVerificationResponse,
    SubmitDataNoDocVerification,
    SubmitPaymentMethod,
    SubmitTransactionData,
    SubmitTransactionForNonExisting,
    UpdateFixedInfo,
    UpdateTopLevelInfo,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ApplicantApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ApplicantApiRaw(api_client)
