# coding: utf-8

"""
    Sumsub API

    Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from sumsub_python_sdk.paths.resources_inspections_inspection_idfieldsvideo_ident_data.get import GetVideoIdentData
from sumsub_python_sdk.apis.tags.inspection_api_raw import InspectionApiRaw


class InspectionApi(
    GetVideoIdentData,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: InspectionApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = InspectionApiRaw(api_client)
